title:       Web Development Rants, Raves, Tips n' Tricks
author:      Rob Martin
linkedin:    http://www.linkedin.com/in/robmartinid8
github:      datadude
source:      ./_source
destination: ./
highlighter: rouge